apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
    name: vote
spec:
  selector:
    matchLabels:
      app: vote
      name: vote
  minReadySeconds: 20
  replicas: 4
  template:
    metadata:
      labels:
        app: vote
        name: vote
    spec:
      containers:
      - image: schoolofdevops/vote:v3
        name: vote
        envFrom:
          - configMapRef:
              name: vote
              optional: true
